spring:
  application:
    name: 1-sprint-mission

  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 30MB

logging:
  level:
    root: INFO

file:
  path:
    user: data/users.dat
    channel: data/channels.dat
    message: data/messages.dat
    binarycontent: data/binarycontents
    readstatus: data/readstatus.dat
    userstatus: data/userstatus.dat

discodeit:
  repository:
    type: file
  storage:
    type: local
    local:
      root-path: .storage/directory
    s3:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
      region: ${S3_REGION}
      bucket: ${S3_BUCKET}

security:
  jwt:
    secret: hihihhihih
    access-token-validity-seconds: 600
    refresh-token-validity-seconds: 6000
