spring:
  application:
    name: 1-sprint-mission

  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      maxFileSize: 10MB
      maxRequestSize: 30MB

logging:
  level:
    root: INFO

file:
  path:
    user: data/users.dat
    channel: data/channels.dat
    message: data/messages.dat
    binarycontent: data/binarycontents
    readstatus: data/readstatus.dat
    userstatus: data/userstatus.dat

discodeit:
  repository:
    type: file
  storage:
    type: local
    local:
      root-path: /path/to/storage/directory
